n1 = int(input('Digite um número: '))
res = n1
print('A tabuada do número {}'.format(n1))
print('{} x 1= {}'.format(n1, res*1))
print('{} x 2= {}'.format(n1, res*2))
print('{} x 3= {}'.format(n1, res*3))
print('{} x 4= {}'.format(n1, res*4))
print('{} x 5= {}'.format(n1, res*5))
print('{} x 6= {}'.format(n1, res*6))
print('{} x 7= {}'.format(n1, res*7))
print('{} x 8= {}'.format(n1, res*8))
print('{} x 9= {}'.format(n1, res*9))
print('{} x 10= {}'.format(n1, res*10))
